### ISSUE TITLE
ContentType for uploads

### ISSUE THREAD

**Issue by markusjohnsson** [joaomoreno/gulp-azure-storage#3]
Thank you for a handy library! I use it to deploy static resources for our application. I had a problem with the content type always becoming `application/octet-stream` for uploaded blobs. Perhaps there should be a way of providing the content type, either supplying a map object, a callback function or just a string. 

However, this worked great for me:

``` diff
upload.js
line 7:
+ var mime = require('mime');

line 32:
- { metadata: { fsmode: file.stat.mode } },
+ { metadata: { fsmode: file.stat.mode }, contentType: mime.lookup(file.relative) },
```

**Comment by joaomoreno** [comment]
Wanna submit a pull request? I would gladly accept it!

**Comment by markusjohnsson** [comment]
Sure, could package it later today! Any thoughts on the need for configuration, or do you think `mime.lookup(..)` is good enough?

**Comment by joaomoreno** [comment]
I'm pretty sure `mime.lookup(...)` is enough. As long as it outputs `application/octet-stream` on the default case.

**Comment by joaomoreno** [comment]
Resolved with #4

**Comment by MarkStokes-outlook** [comment]
Hi,

I am experiencing this same issue. I am uploading javascript (.js) and CSS files to Azure storage, but all my files are going up as application/octet-stream.

I just checked the locally installed version of **gulp-azure-storage** and it includes the contentType metadata option.  However, in my case it is not setting the right metadata.

Can I get any assistance on uploading my files with the correct content type?

```
gulp.watch(['azure/**/*'], function(event){
    return gulp.src('azure/**')
        .pipe(azure.upload({
            account:    settings.account,
            key:        settings.key,
            container:  settings.container
        }));
});
```

**Comment by joaomoreno** [comment]
@MarkStokes-outlook This new issue just got fixed in #6 10 minutes ago. Make sure you get version 0.7.1.

**Comment by MarkStokes-outlook** [comment]
Haha.. OK.  I will update the package... Thanks.

**Comment by MarkStokes-outlook** [comment]
Awesome. That now works.  Thanks.
